apiVersion: v1
kind: Service
metadata:
  name: devsecops-k8s-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: devsecops-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
