rules:
  - id: public-s3-bucket
    pattern: |
      resource "aws_s3_bucket" $BUCKET {
        acl = "public-read"
      }
    message: "Public S3 bucket detected! Use 'private' or 'block_public_acls' instead."
    languages: [terraform]
    severity: ERROR

  - id: overly-permissive-iam-policy
    pattern: |
      statement {
        actions = ["*"]
        resources = ["*"]
      }
    message: "IAM policy allows full access to all resources! Restrict actions and resources."
    languages: [terraform]
    severity: ERROR

  - id: overly-open-security-group
    pattern: |
      resource "aws_security_group_rule" $RULE {
        type        = "ingress"
        cidr_blocks = ["0.0.0.0/0"]
      }
    message: "Security group allows unrestricted inbound access! Limit to specific IPs."
    languages: [terraform]
    severity: WARNING
