name: Deploy K8s App to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up kubectl
      run: |
        az aks get-credentials --resource-group devsecops-lab-rg --name devsecops-aks

    - name: Build and Push Docker Image
      run: |
        docker build -t devsecopsregistry72023.azurecr.io/devsecops-k8s-app:latest k8s-app
        echo "${{ secrets.ACR_PASSWORD }}" | docker login devsecopsregistry72023.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin
        docker push devsecopsregistry72023.azurecr.io/devsecops-k8s-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-app/kubernetes/deployment.yaml
        kubectl apply -f k8s-app/kubernetes/service.yaml
        kubectl apply -f k8s-app/kubernetes/ingress.yaml

    - name: Verify Kubernetes Deployment
      run: |
        kubectl get pods -A
        kubectl get services -A
        kubectl get ingress -A
