name: Deploy DevSecOps Blog

on:
  push:
    branches:
      - main
    paths:
      - 'blog-app/**'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t itjobforme/devsecops-lab:latest ./blog-app

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image to Docker Hub
        run: docker push itjobforme/devsecops-lab:latest

      - name: Deploy via AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "tag:Name=DevSecOps-Blog" \
            --parameters 'commands=["
              sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }},
              sudo docker pull itjobforme/devsecops-lab:latest,
              sudo docker stop devsecops-blog || true,
              sudo docker rm devsecops-blog || true,
              sudo docker run -d -p 80:5000 --name devsecops-blog itjobforme/devsecops-lab:latest
            "]' \
            --region us-east-1
