name: Deploy K8s App to EC2 Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'k8s-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Build and Push Docker Image
      run: |
        set -e
        docker build -t devsecops-k8s-app:latest k8s-app
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 580034872400.dkr.ecr.us-east-1.amazonaws.com
        docker tag devsecops-k8s-app:latest 580034872400.dkr.ecr.us-east-1.amazonaws.com/devsecops-k8s-app:latest
        docker push 580034872400.dkr.ecr.us-east-1.amazonaws.com/devsecops-k8s-app:latest

    - name: Update Kubernetes Deployment via SSM
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=k8s-app-ec2" --query "Reservations[*].Instances[*].InstanceId" --output text)
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["sudo k3s kubectl rollout restart deployment k8s-app"]' \
          --comment "Restart Kubernetes deployment to use latest Docker image" \
          --region us-east-1

    - name: Verify Kubernetes Deployment
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=k8s-app-ec2" --query "Reservations[*].Instances[*].InstanceId" --output text)
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["sudo k3s kubectl get pods -A","sudo k3s kubectl get services -A"]' \
          --comment "Check the status of Kubernetes pods and services" \
          --region us-east-1

    - name: Describe Kubernetes Resources
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=k8s-app-ec2" --query "Reservations[*].Instances[*].InstanceId" --output text)
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["sudo k3s kubectl describe deployment k8s-app","sudo k3s kubectl describe service k8s-app-service"]' \
          --comment "Describe Kubernetes deployment and service" \
          --region us-east-1
