#name: Deploy Terraform on AWS

#on:
 # push:
  #  branches:
   #   - main
    #paths:
     # - 'terraform/**'   

#jobs:
 # terraform:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd terraform
          terraform validate

      - name: Plan Terraform Deployment
        run: |
          cd terraform
          terraform plan

      - name: Apply Terraform Deployment (Only if Plan Succeeds)
        run: |
          cd terraform
          terraform apply -auto-approve
