name: Deploy K8s App to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Set up kubectl for EKS
      run: |
        aws eks update-kubeconfig --name devsecops-eks-cluster --region us-east-1

    - name: Build and Push Docker Image
      run: |
        set -e
        docker build -t devsecops-k8s-app:latest k8s-app
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 580034872400.dkr.ecr.us-east-1.amazonaws.com
        docker tag devsecops-k8s-app:latest 580034872400.dkr.ecr.us-east-1.amazonaws.com/devsecops-k8s-app:latest
        docker push 580034872400.dkr.ecr.us-east-1.amazonaws.com/devsecops-k8s-app:latest

    - name: Deploy to Kubernetes
      run: |
        set -e
        kubectl apply -f k8s-app/kubernetes/deployment.yml
        kubectl apply -f k8s-app/kubernetes/service.yml
        kubectl apply -f k8s-app/kubernetes/ingress.yml

    - name: Verify Kubernetes Deployment
      run: |
        kubectl get pods -A
        kubectl get services -A
        kubectl get ingress -A

    - name: Describe Kubernetes Resources
      run: |
        kubectl describe deployment devsecops-k8s-app
        kubectl describe service devsecops-k8s-service
        kubectl describe ingress devsecops-k8s-ingress
