name: Deploy Azure Infrastructure with Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/azure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure OIDC Environment Variables
      run: |
        echo "Setting up OIDC environment variables"
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Initialize Terraform
      run: |
        cd terraform/azure
        terraform init

    - name: Apply Terraform Configuration
      run: |
        cd terraform/azure
        terraform apply -auto-approve
